In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# import numpy as np
# when we write this, we are basically telling python to call numpy so we can use its functions. np is an alias that we give for it.

In [7]:
arr1 = np.array((5,6,7,8))
print(arr1)

[5 6 7 8]


In [9]:
arr2 = np.array([[1,2,3,4] , [4,5,6,7]])
print(arr2)

[[1 2 3 4]
 [4 5 6 7]]


In [11]:
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [13]:
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#to find shape of the array
arr3.shape

(3, 3)

In [17]:
#to find size of the array
arr3.size

9

In [19]:
#to find dimension of the array
arr3.ndim

2

In [21]:
# to create an array of required size which has only zeros or ones, so that we can add elements later to that

zeros = np.zeros((2,3), dtype = int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# here, (2,3) specifies the size of the array that we want to create, 2 rows and 3 columns and dtype =int specifies the the data type of the elements stored in the array

In [25]:
ones = np.ones((3,3), dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
# to create an array of elements from 0 till before another number
arr_r = np.arange(11)
arr_r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# reshaping

new = np.arange(12)
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
new_reshaped = new.reshape(4,3)
new_reshaped


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
flattened = new_reshaped.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [41]:
raveled = new_reshaped.ravel()
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])